### ISSUE TITLE
FLPConfigForPVS, (MTA BUILD) Failed to sync the workspace.

### ISSUE THREAD

**Issue by SreekanthGudisi** [SAP-samples/cloud-process-visibility#2]
Hi

Is there any prerequisites that we need to follow for Web IDE workspace. Getting the build error while  trying to build the FLPConfigForPVS project. Attached the screenshot.

```
3:44:32 PM (MTA BUILD) Build of "FLPConfigForPVS" started.
3:44:32 PM (Executor) The "Task for mta build" process started.
3:51:26 PM (MTA BUILD) Failed to sync the workspace.
3:51:26 PM (MTA BUILD) Build of "FLPConfigForPVS" failed.
```

THanks, Manju

<img width="1048" alt="Screen Shot 2020-01-27 at 3 52 43 PM" src="https://user-images.githubusercontent.com/23524697/73167126-483c7480-411d-11ea-81d5-b42a632a7278.png">

**Comment by tkhiani** [comment]
I would request you to go over the tutorial and try again: https://developers.sap.com/group.cp-visibility-setup.html

**Comment by SreekanthGudisi** [comment]
@tkhiani I have followed the same tutorial as you referred. Still no luck. Can someone helps me on this from your team.

**Comment by tkhiani** [comment]
This is an issue with SAP WebIDE and I see the following post that can help: https://answers.sap.com/questions/12963548/sap-web-ide-full-stack-build-hdb-keep-status-prere.html

**Comment by manjunathgudisi** [comment]
It's building now. Deployed the FLP on to SAP CP successfully as well.
